import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import {UserProvider} from '@auth0/nextjs-auth0/client';
import '@/styles/globals.css';
import { PrimeReactProvider } from 'primereact/api';

interface RootLayoutProps {
  children: React.ReactNode;
}

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <PrimeReactProvider>
        <UserProvider>
          <body className={inter.className} suppressHydrationWarning={true}>
            {children}
          </body>
        </UserProvider>
      </PrimeReactProvider>
    </html>
  );
}
